import { PersonType } from '@definition/person';
import { SchedWeekType } from '@definition/schedules';
import { FullnameOption, SettingsType } from '@definition/settings';
import { SourceWeekType, Week } from '@definition/sources';
import { VisitingSpeakerType } from '@definition/visiting_speakers';

export const sourceSchema: SourceWeekType = {
  weekOf: '',
  mwb_week_date_locale: {},
  mwb_weekly_bible_reading: {},
  mwb_song_first: '',
  mwb_tgw_talk: {},
  mwb_tgw_bread: {},
  mwb_ayf_count: 0,
  mwb_ayf_part1_type: {},
  mwb_ayf_part1_time: '',
  mwb_ayf_part1: {},
  mwb_ayf_part2_type: {},
  mwb_ayf_part2_time: '',
  mwb_ayf_part2: {},
  mwb_ayf_part3_type: {},
  mwb_ayf_part3_time: '',
  mwb_ayf_part3: {},
  mwb_ayf_part4_type: {},
  mwb_ayf_part4_time: '',
  mwb_ayf_part4: {},
  mwb_song_middle: '',
  mwb_lc_count: 0,
  mwb_lc_count_override: { value: 0, updatedAt: '' },
  mwb_lc_part1_time: '',
  mwb_lc_part1: {},
  mwb_lc_part1_content: {},
  mwb_lc_part1_time_override: { value: '', updatedAt: '' },
  mwb_lc_part1_override: { value: '', updatedAt: '' },
  mwb_lc_part1_content_override: { value: '', updatedAt: '' },
  mwb_lc_part2_time: '',
  mwb_lc_part2: {},
  mwb_lc_part2_content: {},
  mwb_lc_part2_time_override: { value: '', updatedAt: '' },
  mwb_lc_part2_override: { value: '', updatedAt: '' },
  mwb_lc_part2_content_override: { value: '', updatedAt: '' },
  mwb_lc_cbs: {},
  mwb_lc_cbs_time_override: { value: '', updatedAt: '' },
  mwb_co_talk_title: { value: '', updatedAt: '' },
  mwb_song_conclude: '',
  mwb_song_conclude_override: { value: '', updatedAt: '' },
  w_study_date_locale: {},
  w_co_talk_title: { value: '', updatedAt: '' },
  w_study_title: {},
  w_study_opening_song: '',
  w_study_concluding_song: '',
  keep_override: undefined,
};

export const scheduleSchema: SchedWeekType = {
  weekOf: '',
  chairmanMM_A: { value: '', updatedAt: '' },
  chairmanMM_B: { value: '', updatedAt: '' },
  opening_prayerMM: { value: '', updatedAt: '' },
  tgw_talk: { value: '', updatedAt: '' },
  tgw_gems: { value: '', updatedAt: '' },
  bRead_stu_A: { value: '', updatedAt: '' },
  bRead_stu_B: { value: '', updatedAt: '' },
  ass1_stu_A: { value: '', updatedAt: '' },
  ass1_ass_A: { value: '', updatedAt: '' },
  ass1_stu_B: { value: '', updatedAt: '' },
  ass1_ass_B: { value: '', updatedAt: '' },
  ass2_stu_A: { value: '', updatedAt: '' },
  ass2_ass_A: { value: '', updatedAt: '' },
  ass2_stu_B: { value: '', updatedAt: '' },
  ass2_ass_B: { value: '', updatedAt: '' },
  ass3_stu_A: { value: '', updatedAt: '' },
  ass3_ass_A: { value: '', updatedAt: '' },
  ass3_stu_B: { value: '', updatedAt: '' },
  ass3_ass_B: { value: '', updatedAt: '' },
  ass4_stu_A: { value: '', updatedAt: '' },
  ass4_ass_A: { value: '', updatedAt: '' },
  ass4_stu_B: { value: '', updatedAt: '' },
  ass4_ass_B: { value: '', updatedAt: '' },
  lc_part1: { value: '', updatedAt: '' },
  lc_part2: { value: '', updatedAt: '' },
  cbs_conductor: { value: '', updatedAt: '' },
  cbs_reader: { value: '', updatedAt: '' },
  closing_prayerMM: { value: '', updatedAt: '' },
  chairman_WM: { value: '', updatedAt: '' },
  opening_prayerWM: { value: '', updatedAt: '' },
  event_name: { value: '', updatedAt: '' },
  public_talk: { value: 0, updatedAt: '' },
  visiting_speaker_enabled: { value: false, updatedAt: '' },
  speaker_1: { value: '', updatedAt: '' },
  speaker_2: { value: '', updatedAt: '' },
  substitute_speaker: { value: '', updatedAt: '' },
  wtstudy_reader: { value: '', updatedAt: '' },
  chairmanMM_A_name: { value: '', updatedAt: '' },
  chairmanMM_A_display_name: { value: '', updatedAt: '' },
  chairmanMM_B_name: { value: '', updatedAt: '' },
  chairmanMM_B_display_name: { value: '', updatedAt: '' },
  opening_prayerMM_name: { value: '', updatedAt: '' },
  opening_prayerMM_display_name: { value: '', updatedAt: '' },
  tgw_talk_name: { value: '', updatedAt: '' },
  tgw_talk_display_name: { value: '', updatedAt: '' },
  tgw_gems_name: { value: '', updatedAt: '' },
  tgw_gems_display_name: { value: '', updatedAt: '' },
  bRead_stu_A_name: { value: '', updatedAt: '' },
  bRead_stu_A_display_name: { value: '', updatedAt: '' },
  bRead_stu_B_name: { value: '', updatedAt: '' },
  bRead_stu_B_display_name: { value: '', updatedAt: '' },
  ass1_stu_A_name: { value: '', updatedAt: '' },
  ass1_stu_A_display_name: { value: '', updatedAt: '' },
  ass1_ass_A_name: { value: '', updatedAt: '' },
  ass1_ass_A_display_name: { value: '', updatedAt: '' },
  ass1_stu_B_name: { value: '', updatedAt: '' },
  ass1_stu_B_display_name: { value: '', updatedAt: '' },
  ass1_ass_B_name: { value: '', updatedAt: '' },
  ass1_ass_B_display_name: { value: '', updatedAt: '' },
  ass2_stu_A_name: { value: '', updatedAt: '' },
  ass2_stu_A_display_name: { value: '', updatedAt: '' },
  ass2_ass_A_name: { value: '', updatedAt: '' },
  ass2_ass_A_display_name: { value: '', updatedAt: '' },
  ass2_stu_B_name: { value: '', updatedAt: '' },
  ass2_stu_B_display_name: { value: '', updatedAt: '' },
  ass2_ass_B_name: { value: '', updatedAt: '' },
  ass2_ass_B_display_name: { value: '', updatedAt: '' },
  ass3_stu_A_name: { value: '', updatedAt: '' },
  ass3_stu_A_display_name: { value: '', updatedAt: '' },
  ass3_ass_A_name: { value: '', updatedAt: '' },
  ass3_ass_A_display_name: { value: '', updatedAt: '' },
  ass3_stu_B_name: { value: '', updatedAt: '' },
  ass3_stu_B_display_name: { value: '', updatedAt: '' },
  ass3_ass_B_name: { value: '', updatedAt: '' },
  ass3_ass_B_display_name: { value: '', updatedAt: '' },
  ass4_stu_A_name: { value: '', updatedAt: '' },
  ass4_stu_A_display_name: { value: '', updatedAt: '' },
  ass4_ass_A_name: { value: '', updatedAt: '' },
  ass4_ass_A_display_name: { value: '', updatedAt: '' },
  ass4_stu_B_name: { value: '', updatedAt: '' },
  ass4_stu_B_display_name: { value: '', updatedAt: '' },
  ass4_ass_B_name: { value: '', updatedAt: '' },
  ass4_ass_B_display_name: { value: '', updatedAt: '' },
  lc_part1_name: { value: '', updatedAt: '' },
  lc_part1_display_name: { value: '', updatedAt: '' },
  lc_part2_name: { value: '', updatedAt: '' },
  lc_part2_display_name: { value: '', updatedAt: '' },
  cbs_conductor_name: { value: '', updatedAt: '' },
  cbs_conductor_display_name: { value: '', updatedAt: '' },
  cbs_reader_name: { value: '', updatedAt: '' },
  cbs_reader_display_name: { value: '', updatedAt: '' },
  closing_prayerMM_name: { value: '', updatedAt: '' },
  closing_prayerMM_display_name: { value: '', updatedAt: '' },
  chairman_WM_name: { value: '', updatedAt: '' },
  chairman_WM_display_name: { value: '', updatedAt: '' },
  opening_prayerWM_name: { value: '', updatedAt: '' },
  opening_prayerWM_display_name: { value: '', updatedAt: '' },
  speaker_1_name: { value: '', updatedAt: '' },
  speaker_1_display_name: { value: '', updatedAt: '' },
  speaker_2_name: { value: '', updatedAt: '' },
  speaker_2_display_name: { value: '', updatedAt: '' },
  substitute_speaker_name: { value: '', updatedAt: '' },
  substitute_speaker_display_name: { value: '', updatedAt: '' },
  wtstudy_reader_name: { value: '', updatedAt: '' },
  wtstudy_reader_display_name: { value: '', updatedAt: '' },
  midweek_meeting_canceled: { value: false, updatedAt: '' },
  weekend_meeting_canceled: { value: false, updatedAt: '' },
  released: { value: false, updatedAt: '' },
  week_type: { value: Week.NORMAL, updatedAt: '' },
};

export const personSchema: PersonType = {
  _deleted: null,
  person_uid: '',
  person_firstname: { value: '', updatedAt: '' },
  person_lastname: { value: '', updatedAt: '' },
  person_display_name: { value: '', updatedAt: '' },
  male: { value: true, updatedAt: '' },
  female: { value: false, updatedAt: '' },
  birth_date: { value: null, updatedAt: '' },
  assignments: [],
  timeAway: [],
  archived: { value: false, updatedAt: '' },
  disqualified: { value: false, updatedAt: '' },
  email: { value: '', updatedAt: '' },
  address: { value: '', updatedAt: '' },
  phone: { value: '', updatedAt: '' },
  first_month_report: { value: null, updatedAt: '' },
  publisher_baptized: {
    active: { value: false, updatedAt: '' },
    anointed: { value: false, updatedAt: '' },
    other_sheep: { value: true, updatedAt: '' },
    baptism_date: { value: null, updatedAt: '' },
    history: [],
  },
  publisher_unbaptized: {
    active: { value: false, updatedAt: '' },
    history: [],
  },
  midweek_meeting_student: {
    active: { value: true, updatedAt: '' },
    history: [
      {
        id: crypto.randomUUID(),
        start_date: { value: new Date().toISOString(), updatedAt: new Date().toISOString() },
        end_date: { value: null, updatedAt: new Date().toISOString() },
        _deleted: null,
      },
    ],
  },
  privileges: [],
  enrollments: [],
  emergency_contacts: [],
};

export const settingSchema: SettingsType = {
  id: 1,
  cong_settings: {
    country_code: '',
    cong_number: '',
    cong_name: '',
    cong_code: '',
    cong_location: { address: '', lat: 0, lng: 0 },
    cong_new: true,
    cong_circuit: [{ type: 'main', value: '' }],
    display_name_enabled: { value: false, updatedAt: '' },
    fullname_option: { value: FullnameOption.FIRST_BEFORE_LAST, updatedAt: '' },
    circuit_overseer: {
      firstname: { value: '', updatedAt: '' },
      lastname: { value: '', updatedAt: '' },
      display_name: { value: '', updatedAt: '' },
    },
    cong_discoverable: { value: false, updatedAt: '' },
    midweek_meeting: [
      {
        type: 'main',
        class_count: { value: 1, updatedAt: '' },
        opening_prayer_auto_assign: { value: false, updatedAt: '' },
        time: '00:00:00',
        schedule_exact_date_enabled: { value: false, updatedAt: '' },
        weekday: 2,
      },
    ],
    weekend_meeting: [
      {
        type: 'main',
        opening_prayer_auto_assigned: { value: false, updatedAt: '' },
        time: '00:00:00',
        substitute_speaker_enabled: { value: false, updatedAt: '' },
        weekday: 7,
      },
    ],
  },
  user_settings: {
    cong_role: [],
    account_type: '',
    backup_automatic: {
      enabled: { value: true, updatedAt: '' },
      interval: { value: 5, updatedAt: '' },
    },
    hour_credits_enabled: { value: false, updatedAt: '' },
    firstname: { value: '', updatedAt: '' },
    lastname: { value: '', updatedAt: '' },
    theme_follow_os_enabled: { value: false, updatedAt: '' },
    user_avatar: undefined,
    user_local_uid: '',
    user_members_delegate: [],
    user_time_away: [],
    data_view: 'main',
  },
};

export const vistingSpeakerSchema: VisitingSpeakerType = {
  _deleted: null,
  person_uid: '',
  cong_number: '',
  person_display_name: { value: '', updatedAt: '' },
  person_firstname: { value: '', updatedAt: '' },
  person_lastname: { value: '', updatedAt: '' },
  person_notes: { value: '', updatedAt: '' },
  elder: { value: false, updatedAt: '' },
  ministerial_servant: { value: false, updatedAt: '' },
  person_email: { value: '', updatedAt: '' },
  person_phone: { value: '', updatedAt: '' },
  talks: [],
};
