pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - and:
        - author=dependabot[bot]
        - check-success=Code QL
        - check-success=Test application
        - or:
            - title~=^chore\(deps\). [w+]|[^\s]+ from ([\d]+)\..+ to \1\.
            - title~=^feat\(deps\). [w+]|[^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: rebase