pull_request_title: 'chore(locales): updated translation from Crowdin'
pull_request_labels:
  - crowdin
files:
  - source: /src/locales/en/*.json
    ignore:
      - /src/locales/en/source.json
      - /src/locales/en/ui.json
      - /src/locales/en/public_talks.json
      - /src/locales/en/release_notes.json
    translation: /src/locales/%locale%/%original_file_name%
