export const LANGUAGE_LIST = [
  { code: 'x', locale: 'de-DE', name: 'Deutsch' },
  { code: 'e', locale: 'en', name: 'English' },
  { code: 's', locale: 'es-ES', name: 'español' },
  { code: 's', locale: 'es-SSP', name: 'español (de España)' },
  { code: 'f', locale: 'fr-FR', name: 'Français' },
  { code: 'i', locale: 'it-IT', name: 'Italiano' },
  { code: 'mg', locale: 'mg-MG', name: 'Malagasy' },
  { code: 'p', locale: 'pl-PL', name: 'Polski' },
  { code: 't', locale: 'pt-BR', name: 'Português (Brasil)' },
  { code: 'u', locale: 'ru-RU', name: 'русский' },
  { code: 'm', locale: 'ro-RO', name: 'Română' },
  { code: 'tg', locale: 'tl-PH', name: 'Tagalog' },
  { code: 'tnd', locale: 'mg-TND', name: 'Tandroy' },
  { code: 'tnk', locale: 'mg-TNK', name: 'Tankarana' },
  { code: 'ttm', locale: 'mg-TTM', name: 'Tenin’ny Tanana Malagasy' },
  { code: 'tk', locale: 'tr-TR', name: 'Türkçe' },
  { code: 'tw', locale: 'tw-TW', name: 'Twi' },
  { code: 'vz', locale: 'mg-VZ', name: 'Vezo' },
  { code: 'k', locale: 'uk-UA', name: 'Українська' },
  { code: 'chs', locale: 'ch-CHS', name: '中文简体（普通话）', font: 'NotoSans' },
  { code: 'j', locale: 'ja-JP', name: '日本語', font: 'NotoSansJP' },
  { code: 'np', locale: 'ne-NP', name: 'नेपाली', font: 'NotoSans' },
  { code: 'z', locale: 'sv-SE', name: 'Svenska' },
  { code: 'cv', locale: 'ceb-PH', name: 'Cebuano' },
].sort((a, b) => a.code.localeCompare(b.code));

export const APP_ROLES = [
  'admin',
  'coordinator',
  'public_talk_coordinator',
  'lmmo',
  'lmmo-backup',
  'secretary',
  'elder',
  'ms',
  'publisher',
  'view_meeting_schedule',
];

export const VIP_ROLES = ['coordinator', 'public_talk_coordinator', 'lmmo', 'lmmo-backup', 'secretary'];
