// Do not edit directly
// Generated on 9/3/2024, 9:50:20 PM

const styles = {
  font: {
    hugeNumbers: {
      fontSize: '64px',
      textDecoration: 'none',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '96px',
      textIndent: '0px',
      textTransform: 'none',
    },
    bigNumbers: {
      fontSize: '48px',
      textDecoration: 'none',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '56px',
      textIndent: '0px',
      textTransform: 'none',
    },
    h1: {
      fontSize: '24px',
      textDecoration: 'none',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0.24px',
      lineHeight: '28px',
      textIndent: '0px',
      textTransform: 'none',
    },
    h2: {
      fontSize: '20px',
      textDecoration: 'none',
      fontWeight: 550,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '24px',
      textIndent: '0px',
      textTransform: 'none',
    },
    h2Caps: {
      fontSize: '20px',
      textDecoration: 'none',
      fontWeight: 450,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0.2px',
      lineHeight: '24px',
      textIndent: '0px',
      textTransform: 'uppercase',
    },
    h3: {
      fontSize: '18px',
      textDecoration: 'none',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0.18px',
      lineHeight: '24px',
      textIndent: '0px',
      textTransform: 'none',
    },
    h4: {
      fontSize: '16px',
      textDecoration: 'none',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '20px',
      textIndent: '0px',
      textTransform: 'none',
    },
    buttonCaps: {
      fontSize: '15px',
      textDecoration: 'none',
      fontWeight: 450,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0.3px',
      lineHeight: '18px',
      textIndent: '0px',
      textTransform: 'uppercase',
    },
    bodyRegular: {
      fontSize: '16px',
      textDecoration: 'none',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '20px',
      textIndent: '0px',
      textTransform: 'none',
    },
    bodySmallSemibold: {
      fontSize: '14px',
      textDecoration: 'none',
      fontWeight: 520,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '18px',
      textIndent: '0px',
      textTransform: 'none',
    },
    bodySmallRegular: {
      fontSize: '14px',
      textDecoration: 'none',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-0.28px',
      lineHeight: '18px',
      textIndent: '0px',
      textTransform: 'none',
    },
    labelSmallMedium: {
      fontSize: '12px',
      textDecoration: 'none',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-0.12px',
      lineHeight: '14px',
      textIndent: '0px',
      textTransform: 'none',
    },
    labelSmallRegular: {
      fontSize: '12px',
      textDecoration: 'none',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textIndent: '0px',
      textTransform: 'none',
    },
    mobile: {
      h1: {
        fontSize: '20px',
        textDecoration: 'none',
        fontWeight: 550,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '24px',
        textIndent: '0px',
        textTransform: 'none',
      },
      h2: {
        fontSize: '18px',
        textDecoration: 'none',
        fontWeight: 550,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.18px',
        lineHeight: '24px',
        textIndent: '0px',
        textTransform: 'none',
      },
      h2Caps: {
        fontSize: '18px',
        textDecoration: 'none',
        fontWeight: 450,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.18px',
        lineHeight: '22px',
        textIndent: '0px',
        textTransform: 'uppercase',
      },
      h3: {
        fontSize: '16px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '20px',
        textIndent: '0px',
        textTransform: 'none',
      },
      h4: {
        fontSize: '15px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.3px',
        lineHeight: '20px',
        textIndent: '0px',
        textTransform: 'none',
      },
      buttonCaps: {
        fontSize: '14px',
        textDecoration: 'none',
        fontWeight: 450,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.28px',
        lineHeight: '24px',
        textIndent: '0px',
        textTransform: 'uppercase',
      },
      bodyRegular: {
        fontSize: '15px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.15px',
        lineHeight: '20px',
        textIndent: '0px',
        textTransform: 'none',
      },
      bodySmallSemibold: {
        fontSize: '13px',
        textDecoration: 'none',
        fontWeight: 450,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.065px',
        lineHeight: '16px',
        textIndent: '0px',
        textTransform: 'none',
      },
      bodySmallRegular: {
        fontSize: '13px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.065px',
        lineHeight: '16px',
        textIndent: '0px',
        textTransform: 'none',
      },
    },
    pdfTemplates: {
      pageTitle: {
        fontSize: '14px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.14px',
        lineHeight: '16.8px',
        textIndent: '0px',
        textTransform: 'none',
      },
      titleCongregationName: {
        fontSize: '12px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0.12px',
        lineHeight: '14.88px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf10Semibold: {
        fontSize: '10px',
        textDecoration: 'none',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.1px',
        lineHeight: '12px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf10Medium: {
        fontSize: '10px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '12.4px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf10Light: {
        fontSize: '10px',
        textDecoration: 'none',
        fontWeight: 300,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '12px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf10Regular: {
        fontSize: '10px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.1px',
        lineHeight: '12.4px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf9Regular: {
        fontSize: '9px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.18px',
        lineHeight: '9px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf9Semibold: {
        fontSize: '9px',
        textDecoration: 'none',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.18px',
        lineHeight: '10.8px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf8Light: {
        fontSize: '8px',
        textDecoration: 'none',
        fontWeight: 300,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '9.6px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf8Medium: {
        fontSize: '8px',
        textDecoration: 'none',
        fontWeight: 500,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '8px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf12Regular: {
        fontSize: '12px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.12px',
        lineHeight: '12px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf12Bold: {
        fontSize: '12px',
        textDecoration: 'none',
        fontWeight: 700,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.12px',
        lineHeight: '12px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf14BoldCaps: {
        fontSize: '14px',
        textDecoration: 'none',
        fontWeight: 700,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '0px',
        lineHeight: '14px',
        textIndent: '0px',
        textTransform: 'uppercase',
      },
      pdf8Semibold: {
        fontSize: '8px',
        textDecoration: 'none',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.16px',
        lineHeight: '8px',
        textIndent: '0px',
        textTransform: 'none',
      },
      pdf8Regular: {
        fontSize: '8px',
        textDecoration: 'none',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: '-0.16px',
        lineHeight: '8px',
        textIndent: '0px',
        textTransform: 'none',
      },
    },
  },
  colors: {
    printPdfTemplates: {
      blueMain: '#6876beff',
      greenMain: '#498457ff',
      greenLight: '#f1f8f2ff',
      greenNeutral: '#d7e3daff',
    },
  },
};

export default styles;
