const PERSON_MOCK = [
  // ─── Rakoto Family (Malagasy) ──────────────────────────
  {
    gender: 'male',
    firstName: 'Hery',
    lastName: 'Rakoto',
    birthDate: '1975/3/15',
    address: '626 Main Street Phoenix',
    email: 'hery.rakoto@example.com',
    phone: '+81 965-431-3024',
  },
  {
    gender: 'female',
    firstName: 'Voahirana',
    lastName: 'Rakoto',
    birthDate: '1978/5/30',
    address: '626 Main Street Phoenix',
    email: 'voahirana.rakoto@example.com',
    phone: '+81 965-431-3025',
  },
  {
    gender: 'male',
    firstName: 'Tahina',
    lastName: 'Rakoto',
    birthDate: '2001/2/12',
    address: '626 Main Street Phoenix',
    email: 'tahina.rakoto@example.com',
    phone: '+81 965-431-3026',
  },
  // ─── Moretti Family (Italian) ──────────────────────────
  {
    gender: 'male',
    firstName: 'Marco',
    lastName: 'Moretti',
    birthDate: '1979/8/10',
    address: '385 Fifth Street Houston',
    email: 'marco.moretti@example.com',
    phone: '+49 258-627-6644',
  },
  {
    gender: 'female',
    firstName: 'Chiara',
    lastName: 'Moretti',
    birthDate: '1982/6/8',
    address: '385 Fifth Street Houston',
    email: 'chiara.moretti@example.com',
    phone: '+44 373-953-5028',
  },
  // ─── Kovalenko Family (Ukrainian) ─────────────────────
  {
    gender: 'male',
    firstName: 'Oleksiy',
    lastName: 'Kovalenko',
    birthDate: '1974/11/6',
    address: '1642 Ninth Street Washington',
    email: 'oleksiy.kovalenko@example.com',
    phone: '+81 210-652-2785',
  },
  {
    gender: 'female',
    firstName: 'Daryna',
    lastName: 'Kovalenko',
    birthDate: '1977/5/4',
    address: '1642 Ninth Street Washington',
    email: 'daryna.kovalenko@example.com',
    phone: '+49 614-958-9364',
  },
  {
    gender: 'female',
    firstName: 'Ivanna',
    lastName: 'Kovalenko',
    birthDate: '2000/4/20',
    address: '1642 Ninth Street Washington',
    email: 'ivanna.kovalenko@example.com',
    phone: '+49 614-958-9365',
  },
  // ─── Silva Family (Brazilian) ─────────────────────────
  {
    gender: 'male',
    firstName: 'Thiago',
    lastName: 'Silva',
    birthDate: '1978/6/6',
    address: '576 Fifth Street Denver',
    email: 'thiago.silva@example.com',
    phone: '+92 870-217-6201',
  },
  {
    gender: 'female',
    firstName: 'Camila',
    lastName: 'Silva',
    birthDate: '1981/8/4',
    address: '576 Fifth Street Denver',
    email: 'camila.silva@example.com',
    phone: '+49 989-461-8403',
  },
  {
    gender: 'male',
    firstName: 'Rafael',
    lastName: 'Silva',
    birthDate: '2003/3/10',
    address: '576 Fifth Street Denver',
    email: 'rafael.silva@example.com',
    phone: '+49 989-461-8404',
  },
  // ─── Ferreira Family (Portuguese) ─────────────────────
  {
    gender: 'male',
    firstName: 'Diogo',
    lastName: 'Ferreira',
    birthDate: '1980/6/13',
    address: '607 Fourth Street Jacksonville',
    email: 'diogo.ferreira@example.com',
    phone: '+91 759-776-1614',
  },
  {
    gender: 'female',
    firstName: 'Ines',
    lastName: 'Ferreira',
    birthDate: '1983/10/20',
    address: '607 Fourth Street Jacksonville',
    email: 'ines.ferreira@example.com',
    phone: '+61 260-824-4986',
  },
  // ─── Hernandez Family (Mexican) ───────────────────────
  {
    gender: 'male',
    firstName: 'Alejandro',
    lastName: 'Hernandez',
    birthDate: '1976/2/12',
    address: '466 Pine Street San Antonio',
    email: 'alejandro.hernandez@example.com',
    phone: '+92 933-608-5083',
  },
  {
    gender: 'female',
    firstName: 'Valentina',
    lastName: 'Hernandez',
    birthDate: '1979/6/10',
    address: '466 Pine Street San Antonio',
    email: 'valentina.hernandez@example.com',
    phone: '+49 770-658-4885',
  },
  {
    gender: 'male',
    firstName: 'Santiago',
    lastName: 'Hernandez',
    birthDate: '2002/8/25',
    address: '466 Pine Street San Antonio',
    email: 'santiago.hernandez@example.com',
    phone: '+61 731-431-3457',
  },
  // ─── Reyes Family (Filipino) ──────────────────────────
  {
    gender: 'male',
    firstName: 'Carlo',
    lastName: 'Reyes',
    birthDate: '1977/10/26',
    address: '1197 First Street Fort Worth',
    email: 'carlo.reyes@example.com',
    phone: '+1 458-853-7877',
  },
  {
    gender: 'female',
    firstName: 'Althea',
    lastName: 'Reyes',
    birthDate: '1980/8/25',
    address: '1197 First Street Fort Worth',
    email: 'althea.reyes@example.com',
    phone: '+81 507-434-8733',
  },
  {
    gender: 'female',
    firstName: 'Maria',
    lastName: 'Reyes',
    birthDate: '2001/11/30',
    address: '1197 First Street Fort Worth',
    email: 'maria.reyes@example.com',
    phone: '+81 507-434-8734',
  },
  // ─── Braun Family (German) ────────────────────────────
  {
    gender: 'male',
    firstName: 'Tobias',
    lastName: 'Braun',
    birthDate: '1975/3/7',
    address: '1873 Main Street New York',
    email: 'tobias.braun@example.com',
    phone: '+44 468-628-6686',
  },
  {
    gender: 'female',
    firstName: 'Katrin',
    lastName: 'Braun',
    birthDate: '1978/9/5',
    address: '1873 Main Street New York',
    email: 'katrin.braun@example.com',
    phone: '+81 259-957-5711',
  },
  // ─── Johnson Family #1 (American parents) ─────────────
  {
    gender: 'male',
    firstName: 'Robert',
    lastName: 'Johnson',
    birthDate: '1972/4/19',
    address: '1814 Cedar Street Charlotte',
    email: 'robert.johnson@example.com',
    phone: '+91 936-400-4116',
  },
  {
    gender: 'female',
    firstName: 'Emily',
    lastName: 'Johnson',
    birthDate: '1975/6/20',
    address: '1814 Cedar Street Charlotte',
    email: 'emily.johnson@example.com',
    phone: '+1 450-865-6061',
  },
  // ─── Johnson Family #2 (grown children) ───────────────
  {
    gender: 'male',
    firstName: 'Ethan',
    lastName: 'Johnson',
    birthDate: '1996/1/12',
    address: '108 Adams Street Columbus',
    email: 'ethan.johnson@example.com',
    phone: '+49 680-666-9673',
  },
  {
    gender: 'female',
    firstName: 'Sophia',
    lastName: 'Johnson',
    birthDate: '1998/3/3',
    address: '108 Adams Street Columbus',
    email: 'sophia.johnson@example.com',
    phone: '+92 518-863-2863',
  },
  // ─── Williams Family (American) ───────────────────────
  {
    gender: 'male',
    firstName: 'Michael',
    lastName: 'Williams',
    birthDate: '1978/9/11',
    address: '1386 Third Street Los Angeles',
    email: 'michael.williams@example.com',
    phone: '+81 367-320-4960',
  },
  {
    gender: 'female',
    firstName: 'Charlotte',
    lastName: 'Williams',
    birthDate: '1980/6/5',
    address: '1386 Third Street Los Angeles',
    email: 'charlotte.williams@example.com',
    phone: '+49 393-605-6968',
  },
  {
    gender: 'male',
    firstName: 'Noah',
    lastName: 'Williams',
    birthDate: '2002/2/8',
    address: '1386 Third Street Los Angeles',
    email: 'noah.williams@example.com',
    phone: '+1 986-988-5297',
  },
  // ─── Wilson Family (American) ─────────────────────────
  {
    gender: 'male',
    firstName: 'Jackson',
    lastName: 'Wilson',
    birthDate: '1975/1/3',
    address: '568 Tenth Street San Francisco',
    email: 'jackson.wilson@example.com',
    phone: '+1 514-384-3300',
  },
  {
    gender: 'female',
    firstName: 'Madison',
    lastName: 'Wilson',
    birthDate: '1978/5/9',
    address: '568 Tenth Street San Francisco',
    email: 'madison.wilson@example.com',
    phone: '+1 599-432-3048',
  },
  {
    gender: 'male',
    firstName: 'Carter',
    lastName: 'Wilson',
    birthDate: '2001/5/1',
    address: '568 Tenth Street San Francisco',
    email: 'carter.wilson@example.com',
    phone: '+81 405-412-4250',
  },
  // ─── Taylor Family (American) ─────────────────────────
  {
    gender: 'male',
    firstName: 'Logan',
    lastName: 'Taylor',
    birthDate: '1983/8/5',
    address: '1110 Fifth Street Chicago',
    email: 'logan.taylor@example.com',
    phone: '+1 750-526-9455',
  },
  {
    gender: 'female',
    firstName: 'Ava',
    lastName: 'Taylor',
    birthDate: '1985/6/16',
    address: '1110 Fifth Street Chicago',
    email: 'ava.taylor@example.com',
    phone: '+92 802-452-4192',
  },
  // ─── Adams Family (American) ──────────────────────────
  {
    gender: 'male',
    firstName: 'Gabriel',
    lastName: 'Adams',
    birthDate: '1977/9/1',
    address: '1468 Eighth Street Los Angeles',
    email: 'gabriel.adams@example.com',
    phone: '+91 697-236-1544',
  },
  {
    gender: 'female',
    firstName: 'Ella',
    lastName: 'Adams',
    birthDate: '1980/6/16',
    address: '1468 Eighth Street Los Angeles',
    email: 'ella.adams@example.com',
    phone: '+92 802-452-4193',
  },
  // ─── Kelly Family (American) ──────────────────────────
  {
    gender: 'male',
    firstName: 'Lincoln',
    lastName: 'Kelly',
    birthDate: '1976/1/12',
    address: '1110 Fifth Street Chicago',
    email: 'lincoln.kelly@example.com',
    phone: '+49 680-666-9674',
  },
  {
    gender: 'female',
    firstName: 'Harper',
    lastName: 'Kelly',
    birthDate: '1979/3/3',
    address: '1110 Fifth Street Chicago',
    email: 'harper.kelly@example.com',
    phone: '+92 518-863-2864',
  },
  // ─── International Singles ────────────────────────────
  {
    gender: 'female',
    firstName: 'Mialy',
    lastName: 'Andriamahefa',
    birthDate: '1995/10/13',
    address: '1170 Lincoln Street San Diego',
    email: 'mialy.andriamahefa@example.com',
    phone: '+1 623-880-6871',
  },
  {
    gender: 'male',
    firstName: 'Faniry',
    lastName: 'Razafindrakoto',
    birthDate: '1990/10/11',
    address: '996 Oak Street Chicago',
    email: 'faniry.razafindrakoto@example.com',
    phone: '+91 228-363-7806',
  },
  {
    gender: 'female',
    firstName: 'Alessia',
    lastName: 'Conti',
    birthDate: '1997/10/22',
    address: '1701 Eighth Street Columbus',
    email: 'alessia.conti@example.com',
    phone: '+44 468-357-7872',
  },
  {
    gender: 'male',
    firstName: 'Luca',
    lastName: 'Ferretti',
    birthDate: '1991/4/21',
    address: '401 Fourth Street Dallas',
    email: 'luca.ferretti@example.com',
    phone: '+92 468-541-7133',
  },
  {
    gender: 'male',
    firstName: 'Bohdan',
    lastName: 'Tkachenko',
    birthDate: '1993/6/2',
    address: '1578 Fourth Street Columbus',
    email: 'bohdan.tkachenko@example.com',
    phone: '+1 341-597-6694',
  },
  {
    gender: 'female',
    firstName: 'Yaroslava',
    lastName: 'Bondarenko',
    birthDate: '1996/2/5',
    address: '1065 Lincoln Street Dallas',
    email: 'yaroslava.bondarenko@example.com',
    phone: '+61 708-508-4638',
  },
  {
    gender: 'female',
    firstName: 'Larissa',
    lastName: 'Oliveira',
    birthDate: '1994/12/25',
    address: '1163 Pine Street Los Angeles',
    email: 'larissa.oliveira@example.com',
    phone: '+44 254-761-6843',
  },
  {
    gender: 'male',
    firstName: 'Gustavo',
    lastName: 'Souza',
    birthDate: '1992/12/3',
    address: '1946 Oak Street Phoenix',
    email: 'gustavo.souza@example.com',
    phone: '+1 808-757-9867',
  },
  {
    gender: 'female',
    firstName: 'Mariana',
    lastName: 'Lopes',
    birthDate: '1998/8/19',
    address: '1837 Maple Street Indianapolis',
    email: 'mariana.lopes@example.com',
    phone: '+1 240-833-4680',
  },
  {
    gender: 'male',
    firstName: 'Goncalo',
    lastName: 'Mendes',
    birthDate: '1990/7/23',
    address: '356 Pine Street San Jose',
    email: 'goncalo.mendes@example.com',
    phone: '+49 584-501-9302',
  },
  {
    gender: 'female',
    firstName: 'Ximena',
    lastName: 'Flores',
    birthDate: '1997/11/18',
    address: '21 Cedar Street San Francisco',
    email: 'ximena.flores@example.com',
    phone: '+92 957-686-6804',
  },
  {
    gender: 'male',
    firstName: 'Mateo',
    lastName: 'Ramirez',
    birthDate: '1994/9/23',
    address: '164 Elm Street Phoenix',
    email: 'mateo.ramirez@example.com',
    phone: '+91 857-765-4373',
  },
  {
    gender: 'male',
    firstName: 'Miguel',
    lastName: 'Bautista',
    birthDate: '1993/1/14',
    address: '1964 Fifth Street Dallas',
    email: 'miguel.bautista@example.com',
    phone: '+49 980-340-5333',
  },
  {
    gender: 'female',
    firstName: 'Rizalina',
    lastName: 'Villanueva',
    birthDate: '1996/4/20',
    address: '419 Elm Street Seattle',
    email: 'rizalina.villanueva@example.com',
    phone: '+61 837-389-4095',
  },
  {
    gender: 'male',
    firstName: 'Lukas',
    lastName: 'Zimmermann',
    birthDate: '1992/3/25',
    address: '560 Fifth Street Seattle',
    email: 'lukas.zimmermann@example.com',
    phone: '+61 411-514-5320',
  },
  {
    gender: 'female',
    firstName: 'Lena',
    lastName: 'Schaefer',
    birthDate: '1995/4/6',
    address: '590 Lincoln Street Houston',
    email: 'lena.schaefer@example.com',
    phone: '+44 687-435-7119',
  },
  {
    gender: 'female',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    birthDate: '1996/6/16',
    address: '98 Tenth Street San Antonio',
    email: 'yuki.tanaka@example.com',
    phone: '+61 932-569-4853',
  },
  {
    gender: 'male',
    firstName: 'Kwame',
    lastName: 'Mensah',
    birthDate: '1991/8/21',
    address: '1999 Seventh Street San Diego',
    email: 'kwame.mensah@example.com',
    phone: '+44 254-655-6112',
  },
  {
    gender: 'female',
    firstName: 'Priya',
    lastName: 'Sharma',
    birthDate: '1997/11/1',
    address: '25 Sixth Street San Diego',
    email: 'priya.sharma@example.com',
    phone: '+61 333-911-3476',
  },
  {
    gender: 'male',
    firstName: 'Andrei',
    lastName: 'Popescu',
    birthDate: '1993/2/2',
    address: '666 Fourth Street Phoenix',
    email: 'andrei.popescu@example.com',
    phone: '+92 556-625-4398',
  },
  {
    gender: 'female',
    firstName: 'Fatou',
    lastName: 'Diallo',
    birthDate: '1998/6/14',
    address: '55 Madison Street Chicago',
    email: 'fatou.diallo@example.com',
    phone: '+49 212-856-4272',
  },
  {
    gender: 'male',
    firstName: 'Jinsoo',
    lastName: 'Park',
    birthDate: '1994/6/18',
    address: '968 Elm Street San Diego',
    email: 'jinsoo.park@example.com',
    phone: '+91 730-486-3735',
  },
  {
    gender: 'female',
    firstName: 'Amara',
    lastName: 'Okafor',
    birthDate: '1995/12/21',
    address: '1419 Pine Street Columbus',
    email: 'amara.okafor@example.com',
    phone: '+91 322-775-7582',
  },
  {
    gender: 'male',
    firstName: 'Ravi',
    lastName: 'Patel',
    birthDate: '1990/11/6',
    address: '926 Elm Street Jacksonville',
    email: 'ravi.patel@example.com',
    phone: '+92 378-326-3439',
  },
  {
    gender: 'female',
    firstName: 'Annika',
    lastName: 'Lindqvist',
    birthDate: '1997/9/17',
    address: '1423 Main Street Jacksonville',
    email: 'annika.lindqvist@example.com',
    phone: '+1 465-379-7226',
  },
  {
    gender: 'male',
    firstName: 'Kofi',
    lastName: 'Asante',
    birthDate: '1992/12/23',
    address: '1957 Cedar Street Seattle',
    email: 'kofi.asante@example.com',
    phone: '+49 550-430-8269',
  },
  {
    gender: 'female',
    firstName: 'Meiling',
    lastName: 'Chen',
    birthDate: '1996/4/22',
    address: '1094 Adams Street San Antonio',
    email: 'meiling.chen@example.com',
    phone: '+44 926-778-4653',
  },
  {
    gender: 'male',
    firstName: 'Sergei',
    lastName: 'Volkov',
    birthDate: '1991/6/26',
    address: '1486 Second Street Chicago',
    email: 'sergei.volkov@example.com',
    phone: '+49 328-635-8057',
  },
  {
    gender: 'female',
    firstName: 'Aiko',
    lastName: 'Watanabe',
    birthDate: '1998/6/17',
    address: '1506 Jefferson Street Austin',
    email: 'aiko.watanabe@example.com',
    phone: '+91 458-289-9756',
  },
  {
    gender: 'male',
    firstName: 'Emmanuel',
    lastName: 'Mbeki',
    birthDate: '1993/11/10',
    address: '1795 Seventh Street Columbus',
    email: 'emmanuel.mbeki@example.com',
    phone: '+44 540-488-4436',
  },
  {
    gender: 'female',
    firstName: 'Ingrid',
    lastName: 'Haugen',
    birthDate: '1994/3/15',
    address: '447 Ninth Street Dallas',
    email: 'ingrid.haugen@example.com',
    phone: '+92 896-206-1901',
  },
  {
    gender: 'male',
    firstName: 'Tomasz',
    lastName: 'Kowalski',
    birthDate: '1992/5/1',
    address: '789 Main Street Dallas',
    email: 'tomasz.kowalski@example.com',
    phone: '+1 251-564-2643',
  },
  {
    gender: 'female',
    firstName: 'Amina',
    lastName: 'Yusuf',
    birthDate: '1997/3/9',
    address: '1577 Seventh Street Phoenix',
    email: 'amina.yusuf@example.com',
    phone: '+61 857-625-2029',
  },
  {
    gender: 'male',
    firstName: 'Kenji',
    lastName: 'Nakamura',
    birthDate: '1990/5/9',
    address: '14 Main Street Phoenix',
    email: 'kenji.nakamura@example.com',
    phone: '+1 394-401-1757',
  },
  // ─── American/English Singles ─────────────────────────
  {
    gender: 'male',
    firstName: 'Elijah',
    lastName: 'Stewart',
    birthDate: '1991/8/19',
    address: '554 Seventh Street Austin',
    email: 'elijah.stewart@example.com',
    phone: '+91 453-220-4258',
  },
  {
    gender: 'male',
    firstName: 'Daniel',
    lastName: 'Cook',
    birthDate: '1983/2/5',
    address: '466 Sixth Street Philadelphia',
    email: 'daniel.cook@example.com',
    phone: '+91 207-801-7417',
  },
  {
    gender: 'male',
    firstName: 'Henry',
    lastName: 'Hill',
    birthDate: '1986/7/28',
    address: '1078 Sixth Street Los Angeles',
    email: 'henry.hill@example.com',
    phone: '+81 351-413-9369',
  },
  {
    gender: 'female',
    firstName: 'Natalie',
    lastName: 'Harris',
    birthDate: '1996/6/1',
    address: '1553 Sixth Street San Diego',
    email: 'natalie.harris@example.com',
    phone: '+44 434-406-8551',
  },
  {
    gender: 'male',
    firstName: 'Jack',
    lastName: 'Ward',
    birthDate: '1995/4/8',
    address: '240 Jefferson Street San Jose',
    email: 'jack.ward@example.com',
    phone: '+61 386-511-8949',
  },
  {
    gender: 'female',
    firstName: 'Harper',
    lastName: 'Turner',
    birthDate: '1991/10/3',
    address: '639 Fourth Street Denver',
    email: 'harper.turner@example.com',
    phone: '+92 657-388-7474',
  },
  {
    gender: 'male',
    firstName: 'Mason',
    lastName: 'Parker',
    birthDate: '1990/11/16',
    address: '1656 Eighth Street Denver',
    email: 'mason.parker@example.com',
    phone: '+49 968-571-2475',
  },
  {
    gender: 'female',
    firstName: 'Aria',
    lastName: 'Roberts',
    birthDate: '1998/12/24',
    address: '1705 Pine Street Jacksonville',
    email: 'aria.roberts@example.com',
    phone: '+49 638-976-6904',
  },
  {
    gender: 'male',
    firstName: 'Owen',
    lastName: 'Fisher',
    birthDate: '1993/12/7',
    address: '236 Lincoln Street Jacksonville',
    email: 'owen.fisher@example.com',
    phone: '+44 618-916-5243',
  },
  {
    gender: 'male',
    firstName: 'Benjamin',
    lastName: 'Foster',
    birthDate: '1990/9/16',
    address: '244 Second Street Austin',
    email: 'benjamin.foster@example.com',
    phone: '+91 624-944-2089',
  },
  {
    gender: 'female',
    firstName: 'Hannah',
    lastName: 'Robinson',
    birthDate: '1995/4/19',
    address: '1813 Ninth Street Chicago',
    email: 'hannah.robinson@example.com',
    phone: '+44 663-850-4302',
  },
  {
    gender: 'male',
    firstName: 'Jacob',
    lastName: 'Cooper',
    birthDate: '1993/9/14',
    address: '571 Washington Street Charlotte',
    email: 'jacob.cooper@example.com',
    phone: '+44 907-679-1302',
  },
  {
    gender: 'male',
    firstName: 'Eli',
    lastName: 'Bennett',
    birthDate: '1995/10/2',
    address: '1858 Madison Street San Antonio',
    email: 'eli.bennett@example.com',
    phone: '+92 260-518-7256',
  },
  {
    gender: 'female',
    firstName: 'Grace',
    lastName: 'Perry',
    birthDate: '1998/12/1',
    address: '1466 Oak Street Los Angeles',
    email: 'grace.perry@example.com',
    phone: '+44 371-964-4017',
  },
  {
    gender: 'male',
    firstName: 'Nathan',
    lastName: 'Dixon',
    birthDate: '1990/9/25',
    address: '1110 Seventh Street San Diego',
    email: 'nathan.dixon@example.com',
    phone: '+61 456-307-5568',
  },
  {
    gender: 'male',
    firstName: 'Ethan',
    lastName: 'Fletcher',
    birthDate: '1991/10/26',
    address: '439 Pine Street San Antonio',
    email: 'ethan.fletcher@example.com',
    phone: '+1 232-621-9938',
  },
  {
    gender: 'male',
    firstName: 'Jonathan',
    lastName: 'Pierce',
    birthDate: '1991/1/6',
    address: '1581 Oak Street Austin',
    email: 'jonathan.pierce@example.com',
    phone: '+81 693-260-7234',
  },
  {
    gender: 'female',
    firstName: 'Samantha',
    lastName: 'Howard',
    birthDate: '1994/9/18',
    address: '756 Washington Street New York',
    email: 'samantha.howard@example.com',
    phone: '+91 688-478-9459',
  },
  {
    gender: 'female',
    firstName: 'Nora',
    lastName: 'Mills',
    birthDate: '1998/9/18',
    address: '940 Oak Street San Jose',
    email: 'nora.mills@example.com',
    phone: '+44 767-262-6860',
  },
  // ─── Cohen Family (Hebrew) ────────────────────────────
  {
    gender: 'male',
    firstName: 'David',
    lastName: 'Cohen',
    birthDate: '1981/4/23',
    address: '847 Third Street Boston',
    email: 'david.cohen@example.com',
    phone: '+1 617-555-1234',
  },
  {
    gender: 'female',
    firstName: 'Sarah',
    lastName: 'Cohen',
    birthDate: '1984/2/15',
    address: '847 Third Street Boston',
    email: 'sarah.cohen@example.com',
    phone: '+1 617-555-1235',
  },
  {
    gender: 'female',
    firstName: 'Yael',
    lastName: 'Cohen',
    birthDate: '2006/9/10',
    address: '847 Third Street Boston',
    email: 'yael.cohen@example.com',
    phone: '+1 617-555-1236',
  },
];

export default PERSON_MOCK;
