export const TABLE_ENCRYPTION_MAP = {
  persons: {
    person_firstname: 'shared',
    person_lastname: 'shared',
    person_display_name: 'shared',
    male: 'shared',
    female: 'shared',
    birth_date: 'private',
    assignments: 'shared',
    timeAway: 'shared',
    archived: 'shared',
    disqualified: 'private',
    email: 'shared',
    address: 'shared',
    phone: 'shared',
    publisher_baptized: 'shared',
    publisher_unbaptized: 'shared',
    midweek_meeting_student: 'shared',
    privileges: 'shared',
    enrollments: 'shared',
    emergency_contacts: 'shared',
  },
  app_settings: {
    cong_settings: {
      country_code: 'public',
      cong_number: 'public',
      cong_name: 'public',
      cong_master_key: 'private',
      cong_access_code: 'shared',
      cong_location: 'public',
      cong_new: 'public',
      cong_circuit: 'public',
      cong_discoverable: 'public',
      fullname_option: 'shared',
      short_date_format: 'shared',
      display_name_enabled: 'shared',
      schedule_exact_date_enabled: 'shared',
      time_away_public: 'shared',
      source_material_auto_import: 'shared',
      special_months: 'shared',
      midweek_meeting: {
        type: 'public',
        weekday: 'public',
        time: 'public',
        class_count: 'shared',
        opening_prayer_auto_assigned: 'shared',
        closing_prayer_auto_assigned: 'shared',
        aux_class_counselor_default: 'shared',
      },
      weekend_meeting: {
        type: 'public',
        weekday: 'public',
        time: 'public',
        opening_prayer_auto_assigned: 'shared',
        substitute_speaker_enabled: 'shared',
        w_study_conductor_default: 'shared',
        substitute_w_study_conductor_displayed: 'shared',
        consecutive_monthly_parts_notice_shown: 'shared',
        outgoing_talks_schedule_public: 'shared',
      },
      circuit_overseer: 'shared',
      language_groups: 'shared',
      format_24h_enabled: 'shared',
      week_start_sunday: 'shared',
      attendance_online_record: 'shared',
      responsabilities: 'shared',
    },
  },
};
