name: New translation language for the Organized app
description: Request a new language to be added to Crowdin platform
labels: [i18n]
body:
  - type: markdown
    attributes:
      value: |
        Add an issue title with this format: [Language] - New Language Request
