import { useState } from 'react';
import { useRecoilValue } from 'recoil';
import { VisitingSpeakerType } from '@definition/visiting_speakers';
import { autoGenerateDisplayNameState, congNameState } from '@states/settings';
import { buildPersonFullname } from '@utils/common';
import { personsActiveState } from '@states/persons';
import { personIsElder } from '@services/app/persons';

const useSpeakerDetails = (speaker: VisitingSpeakerType) => {
  const autogenerateDN = useRecoilValue(autoGenerateDisplayNameState);
  const persons = useRecoilValue(personsActiveState);
  const congName = useRecoilValue(congNameState);

  const [isEdit, setIsEdit] = useState(false);

  const person = persons.find((record) => record.person_uid === speaker.person_uid);

  const personName = autogenerateDN
    ? buildPersonFullname(speaker.person_lastname.value, speaker.person_firstname.value)
    : speaker.person_displayName.value;

  const isElder = personIsElder(person);

  const handleToggleEdit = () => setIsEdit((prev) => !prev);

  return { personName, isElder, congName, handleToggleEdit, isEdit };
};

export default useSpeakerDetails;
