import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: '20px',
    height: '100%',
    width: '100%',
  },
  header: {
    padding: '5px 16px',
    backgroundColor: '#6876BE',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopLeftRadius: '6px',
    borderTopRightRadius: '6px',
  },
  headerTitleContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '5px',
  },
  headerTittle: {
    color: '#FEFEFE',
    fontWeight: 'medium',
    fontSize: '14px',
  },
  headerCongregation: {
    color: '#FEFEFE',
    fontWeight: 'medium',
    fontSize: '12px',
  },
  weekContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    borderBottom: '1px solid #D5DFFD',
    borderRight: '1px solid #D5DFFD',
    borderLeft: '1px solid #D5DFFD',
  },
  dateContainer: {
    backgroundColor: '#F2F5FF',
    width: '60px',
    paddingLeft: '4px',
    paddingRight: '4px',
    borderRight: '1px solid #D5DFFD',
    display: 'flex',
    justifyContent: 'center',
    fontWeight: 'semibold',
  },
  dateText: {
    color: '#3B4CA3',
    fontSize: '9px',
    textAlign: 'center',
    fontWeight: '600',
  },
  meetingPartSection: {
    flex: 1,
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    paddingTop: '8px',
    paddingBottom: '8px',
  },
  meetingPartSectionRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  meetingPartContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  meetingPartLabel: {
    width: '90px',
    color: '#757575',
    fontSize: '9px',
    fontWeight: '400',
  },
  meetingPartName: {
    color: '#222222',
    fontSize: '10px',
    fontWeight: '400',
    width: '130px',
  },
  meetingPartSong: {
    color: '#222222',
    fontSize: '9px',
    fontWeight: '600',
    width: '130px',
  },
  lineHorizontal: {
    borderBottom: '1px solid #D5DFFD',
    marginTop: '5px',
    marginBottom: '5px',
  },
  lineVertical: {
    marginTop: '10px',
    marginBottom: '10px',
    borderLeft: '1px solid #D5DFFD',
  },
  talkContainer: {
    width: '244px',
    marginTop: '10px',
    marginBottom: '10px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingRight: '10px',
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
  },
  talkTitleContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '5px',
  },
  circuitOverseerTalkContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  talkTitle: {
    width: '230px',
    color: '#3B4CA3',
    fontSize: '10px',
    fontWeight: 'semibold',
  },
  talkNumber: {
    color: '#8391BD',
    fontSize: '8px',
    fontWeight: 'medium',
    flexWrap: 'nowrap',
  },
  speakerContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '16px',
  },
  speaker: {
    fontSize: '10px',
    fontWeight: 'medium',
    color: '#222222',
  },
  speakerCongregation: {
    fontSize: '9px',
    fontWeight: '300',
    color: '#222222',
  },
  substituteSpeakerContainer: {
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    padding: '4px 8px',
    gap: '2px',
    backgroundColor: '#F2F5FF',
    borderRadius: '2px',
    flexWrap: 'wrap',
  },
  labelDefault: {
    fontSize: '8px',
    fontWeight: 'light',
    color: '#222222',
  },
  substituteName: {
    fontSize: '8px',
    fontWeight: 'medium',
    color: '#222222',
  },
  songContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: '2px',
    marginLeft: '8px',
    alignItems: 'center',
  },
  openingSongContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '2px',
  },
  openingSongTitle: {
    fontWeight: '400',
    fontSize: '9px',
    color: '#3B4CA3',
  },
});

export default styles;
