export type BackupOrganizedType = {
  name: string;
  exported: string;
  version: string;
  data: {
    [table: string]: object[];
  };
};

export type BackupCPEType = {
  persons: {
    person_uid: string;
    person_name: string;
    person_displayName: string;
    isMale: boolean;
    isFemale: boolean;
    isUnavailable: boolean;
    assignments: { code: number }[];
    isMoved: boolean;
    isDisqualified: boolean;
    birthDate: string;
    isAnointed: boolean;
    isOtherSheep: boolean;
    isBaptized: boolean;
    immersedDate: string;
    email: string;
    address: string;
    phone: string;
    spiritualStatus: {
      statusId: string;
      status: string;
      startDate: string;
      endDate: string;
    }[];
    otherService: {
      serviceId: string;
      service: string;
      startDate: string;
      endDate: string;
    }[];
    firstMonthReport: string;
  }[];
  fieldServiceGroup: {
    fieldServiceGroup_uid: string;
    isCurrent: boolean;
    groups: {
      group_uid: string;
      persons: {
        person_uid: string;
        isOverseer: boolean;
        isAssistant: boolean;
      }[];
    }[];
    deleted: boolean;
  }[];
  visiting_speakers: {
    cong_name: string;
    cong_number: number;
    cong_speakers: {
      person_uid: string;
      person_name: string;
      person_displayName: string;
      is_elder: boolean;
      is_ms: boolean;
      talks: number[];
      is_unavailable: boolean;
      is_deleted: boolean;
      email: string;
      phone: string;
    }[];
    is_local: boolean;
    is_deleted: boolean;
    request_status: string;
  }[];
  branchReports: {
    report_uid: string;
    report: string;
    service_year: string;
    month: string;
    details: {
      isFinalized: boolean;
      isSubmitted: boolean;
      activePublishers: number;
      weekendMeetingAttendanceAvg: number;
      totalReports: number;
      totalPlacements: number;
      totalVideos: number;
      totalHours: number;
      totalReturnVisits: number;
      totalBibleStudies: number;
      publishersReports: number;
      publishersPlacements: number;
      publishersVideos: number;
      publishersHours: number;
      publishersReturnVisits: number;
      publishersBibleStudies: number;
      auxPioneersReports: number;
      auxPioneersPlacements: number;
      auxPioneersVideos: number;
      auxPioneersHours: number;
      auxPioneersReturnVisits: number;
      auxPioneersBibleStudies: number;
      FRReports: number;
      FRPlacements: number;
      FRVideos: number;
      FRHours: number;
      FRReturnVisits: number;
      FRBibleStudies: number;
    };
  }[];
  fieldServiceReports: {
    uid: string;
    service_year: string;
    person_uid: string;
    months: {
      uid: string;
      month_value: string;
      hours: string;
      hourCredit: string;
      bibleStudies: number;
      minutes: string;
      placements: string;
      returnVisits: string;
      videos: string;
      comments: string;
    }[];
  }[];
  meetingAttendance: {
    uid: string;
    service_year: string;
    month_value: string;
    midweek_meeting: { index: number; count: string }[];
    weekend_meeting: { index: number; count: string }[];
  }[];
  sources: {
    weekOf: string;
    mwb_week_date_locale: { [lang: string]: string };
    mwb_weekly_bible_reading: { [lang: string]: string };
    mwb_song_first: number;
    mwb_tgw_talk: { [lang: string]: string };
    mwb_tgw_bread: { [lang: string]: string };
    mwb_ayf_count: number;
    mwb_ayf_part1_type: { [lang: string]: number };
    mwb_ayf_part1_time: number;
    mwb_ayf_part1: { [lang: string]: string };
    mwb_ayf_part2_type: { [lang: string]: number };
    mwb_ayf_part2_time: number;
    mwb_ayf_part2: { [lang: string]: string };
    mwb_ayf_part3_type: { [lang: string]: number };
    mwb_ayf_part3_time: number;
    mwb_ayf_part3: { [lang: string]: string };
    mwb_ayf_part4_type: { [lang: string]: number };
    mwb_ayf_part4_time: number;
    mwb_ayf_part4: { [lang: string]: string };
    mwb_song_middle: number;
    mwb_lc_count: number;
    mwb_lc_count_override: number;
    mwb_lc_part1_time: number;
    mwb_lc_part1: { [lang: string]: string };
    mwb_lc_part1_content: { [lang: string]: string };
    mwb_lc_part1_time_override: number;
    mwb_lc_part1_override: { [lang: string]: string };
    mwb_lc_part1_content_override: { [lang: string]: string };
    mwb_lc_part2_time: number;
    mwb_lc_part2: { [lang: string]: string };
    mwb_lc_part2_content: { [lang: string]: string };
    mwb_lc_part2_time_override: number;
    mwb_lc_part2_override: { [lang: string]: string };
    mwb_lc_part2_content_override: { [lang: string]: string };
    mwb_lc_cbs: { [lang: string]: string };
    mwb_lc_cbs_time_override: string;
    mwb_co_talk_title: string;
    mwb_song_conclude: number;
    mwb_song_conclude_override: string;
    w_study_date_locale: { [lang: string]: string };
    w_co_talk_title: string;
    w_talk_title_override: string;
    w_study_title: { [lang: string]: string };
    w_study_opening_song: string;
    w_study_concluding_song: string;
  }[];
  sched: {
    weekOf: string;
    week_type: number;
    noMMeeting: boolean;
    noWMeeting: boolean;
    chairmanMM_A: string;
    chairmanMM_B: string;
    cbs_conductor: string;
    tgw_talk: string;
    tgw_gems: string;
    lc_part1: string;
    lc_part2: string;
    lc_part3: string;
    cbs_reader: string;
    opening_prayerMM: string;
    closing_prayerMM: string;
    bRead_stu_A: string;
    bRead_stu_B: string;
    ass1_stu_A: string;
    ass1_stu_B: string;
    ass1_ass_A: string;
    ass1_ass_B: string;
    ass2_stu_A: string;
    ass2_stu_B: string;
    ass2_ass_A: string;
    ass2_ass_B: string;
    ass3_stu_A: string;
    ass3_stu_B: string;
    ass3_ass_A: string;
    ass3_ass_B: string;
    ass4_stu_A: string;
    ass4_stu_B: string;
    ass4_ass_A: string;
    ass4_ass_B: string;
    public_talk: number;
    public_talk_title: string;
    speaker_1: string;
    speaker_2: string;
    substitute_speaker: string;
    chairman_WM: string;
    opening_prayerWM: string;
    wtstudy_reader: string;
    is_visiting_speaker: boolean;
  }[];
};
