name: Deploy app to Live
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dev_deploy:
    name: Build and Deploy to Production
    if: ${{ github.repository == 'sws2apps/organized-app' && github.ref == 'refs/heads/main' }}
    environment:
      name: Live (organized-app.com)
      url: https://organized-app.com
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js LTS version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: lts/Krypton

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release to version and build App
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy project to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
