name: NodeJSScan

on:
  schedule:
    - cron: '0 12 * * 4'

permissions:
  contents: read

jobs:
  nodejsscan:
    name: NodeJS Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@231750a435d85095d33be7d192d52ec650625146
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463
        with:
          sarif_file: results.sarif
